version: "3.9"

services:
  mysql-server:
    container_name: mysql-batch-server
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root@1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: pswd
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - my-data-volume:/var/lib/mysql
    networks:
      - my-network
  app:
    container_name: app-server
    depends_on:
      mysql-server:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql-server
      MYSQL_USER_NAME: root
      MYSQL_PASSWORD: root@1234
    ports:
      - "8080:8080"
    networks:
      - my-network
    restart: on-failure

volumes:
  my-data-volume:

networks:
  my-network:
    name: my-network
    driver: bridge